from geopy.geocoders import Bing
from geopy.exc import GeocoderTimedOut
import json

# Chave da API do Bing Maps (substitua pela sua chave)
bing_api_key = "AkNeIUis2cBj3OJ7AwOLhQsnnJN-mqDgpy9U69l7C9wmSGBarAlNx5r_Dm_GvKTD"

# Lista de endereços
enderecos = [
    "Av. Visconde de Suassuna, 500, Santo Amaro, RECIFE" ,
"Av. Visconde de Suassuna, 265, Santo Amaro, RECIFE" ,
"AV VISCONDE DE SUASSUNA, 265, SANTO AMARO, RECIFE" ,
"Ave Goiás, 1.805, São Caetano do Sul, SÃO PAULO" ,
"Rua Orlando Coelho da Silva,31 , Porta Larga , JABOATÃO DOS GUARARAPES" ,
"Rua Jader de Andrade, 419, Casa Forte, RECIFE" ,
"Av. Presidente Kennedy, 679 , Candeias, JABOATÃO DOS GUARARAPES" ,
"None, None, JABOATÃO DOS GUARARAPES" ,
"Avenida Cicero Batista de Oliveira, n° 5107, São José, GRAVATÁ" ,
"None, None, OLINDA" ,
"Rua da Harmonia, 878 , Casa Amarela, RECIFE" ,
"Rua João Fernandes Vieira, 356 , Boa Vista , RECIFE" ,
"Estrada de Aldeia,9012, Vera Cruz , CAMARAGIBE" ,
"Rua Projetada, 14, Matriz, VITÓRIA DE SANTO ANTÃO" ,
"Rua Comendador José Didier, 27, Bairro de Piedade, JABOATÃO DOS GUARARAPES" ,
"Av. República do Líbano, n º 251, Torre A, Sala 2805, Pina, RECIFE" ,
"Rua Tabaiares, 360, Ilha do Retiro, RECIFE" ,
"Rua Joaquim Nabuco, 677, Derby, RECIFE" ,
"Avenida da Integração Ayrton Senna, 284, São José, PETROLINA" ,
"Rua Marcondes Pereira, 625, Joaquim Távora, FORTALEZA" ,
"AV PARIS, 153/1, UNIVERSITARIO, CARUARU" ,
"None, None, GOIANA" ,
"None, None, GOIANA" ,
"None, None, GOIANA" ,
"Avenida André Vidal de Negreiros, 88 , Centro, GOIANA" ,
"Rua Olímpio Virgínio, 88, Centro, PETROLINA" ,
"Avenida Duque de Godoy Sousa, 001 – Loja 124, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Antônio Santana Filho, 353 , Centro, PETROLINA" ,
"Avenida Nossa Senhora das Grotas, 155, Cohab São Francisco, PETROLINA" ,
"Rua Emília Lamas Grandi, 131, Bela Vista, MORENO" ,
"Itajaí, 465 , Imbiribeira, RECIFE" ,
"Rua Coronel Antônio Cavalcante, 157 , Centro, BUIQUE" ,
"Avenida Engenheiro Domingos Ferreira, 2.391 , Boa Viagem, RECIFE" ,
"Rua José Alves Bezerra, 430 , Guararapes, JABOATÃO DOS GUARARAPES" ,
"None, None, PETROLINA" ,
"Rua Sete de Setembro, 238 , Boa Vista, RECIFE" ,
"AVENIDA AGAMENON MAGALHÃES, 1.233, MAURÍCIO DE NASSAU, CARUARU" ,
"Avenida Tancredo de Almeida Neves, 379, Centro, BUIQUE" ,
"Praça Major França,38, Centro, BUIQUE" ,
"Travessa da Simpatia, 14, Centro, PETROLINA" ,
"Avenida Engenheiro Domingos Ferreira, 683, Pina, RECIFE" ,
"Avenida Dr Cláudio José Gueiros Leite, 10.050 , Maria Farinha, PAULISTA" ,
"Avenida Visconde de Albuquerque, 754 , Madalena, RECIFE" ,
"Av. Lins Petit, 140, RECIFE" ,
"Estrada da Batalha, 684 , PRAZERES, JABOATÃO DOS GUARARAPES" ,
"Rua Jean Emile Favre, 885 , Ipsep, RECIFE" ,
"Rua 15 de Novembro, 100 , Centro, CARUARU" ,
"Avenida Engenheiro Domingos Ferreira, 4.023, BOA VIAGEM, RECIFE" ,
"Rua Joaquim Nabuco, 344 , GRAÇAS, RECIFE" ,
"Rua Taim, 246 , Bongi, RECIFE" ,
"Avenida Monsenhor Ângelo Sampaio , 310, Centro, PETROLINA" ,
"Praça Dom Pedro II,80, Boa Vista, GARANHUNS" ,
"Avenida Doutor Júlio Maranhão, 777 , PRAZERES, JABOATÃO DOS GUARARAPES" ,
"Rua Amaury De Medeiros –182, Santo Antônio, GARANHUNS" ,
"Avenida Caxangá,1753 , Cordeiro, RECIFE" ,
"na Avenida Perimetral, 05 , Aluísio Pinto, GARANHUNS" ,
"Avenida Norte Miguel Arraes, 6.669, CASA AMARELA, RECIFE" ,
"Avenida Doutor Idelfonso Lopes, 228 , Heliópolis, GARANHUNS" ,
"Avenida Governador Carlos de Lima Cavalcanti, 843  , BAIRRO NOVO, OLINDA" ,
"Praça Mestre Dominguinhos, S/N , São José, GARANHUNS" ,
"Rua Tenente João Cícero, 301 – CXPST 8, BOA VIAGEM, RECIFE" ,
"Rua do Alto, 15, Dois Unidos, RECIFE" ,
"Avenida Belmino Correa, 660 , Centro, CAMARAGIBE" ,
"Rodovia PE 49, Km 19,5, Ponta de Pedras, GOIANA" ,
"Praça João Pessoa, 12, Santo Antônio, GARANHUNS" ,
"None, None, GARANHUNS" ,
"Avenida Santo Antônio, 354 , Santo Antônio, GARANHUNS" ,
"Avenida Santo Antônio, 354 , Santo Antônio, GARANHUNS" ,
"Avenida Santa Rosa, 699 , Heliópolis, GARANHUNS" ,
"Rua Manoel Borba, 68 , Santo Antônio, GARANHUNS" ,
"Avenida Ernesto Dourado, 582, Heliópolis, GARANHUNS" ,
"Rua Imperial,137, Matriz, VITÓRIA DE SANTO ANTÃO" ,
"Rua Imperial, 153 , Matriz, VITÓRIA DE SANTO ANTÃO" ,
"Avenida Dr. Pedro Jordão, 670, Maurício de Nassau, CARUARU" ,
"Avenida Monsenhor Ângelo Sampaio, 407 , Maria Auxiliadora, PETROLINA" ,
"Rua Gervásio Pires, 881 , Santo Amaro, RECIFE" ,
"Rua Rita Nunes de Araújo, 34 , São Cristóvão, SANTA CRUZ DO CAPIBARIBE" ,
"Doutor José Mariano, 199 , Santo Antônio, GARANHUNS" ,
"Praça Deputado Henrique Pinto, 19, Nossa Senhora das Dores, CARUARU" ,
"Rua Quinze de Novembro, 112-A (Térreo), Nossa Senhora das Dores, CARUARU" ,
"None, None, SURUBIM" ,
"Rua Antônio Benvindo de Barros, 198, Centro, SURUBIM" ,
"Avenida Brasil, 602 , Universitário, CARUARU" ,
"Avenida Dorival José Pereira, 1010, Parque das Feiras, TORITAMA" ,
"Rua Capitão Rebelinho, 182, Pina, RECIFE" ,
"Avenida Marechal Juarez Távora, 440 , Boa Viagem, RECIFE" ,
"Rua João Batista,89, Centro, SURUBIM" ,
"Rua Agamenon Magalhães, 132 , Centro, SURUBIM" ,
"Avenida Visconde de Suassuna, 337 , Boa Vista, RECIFE" ,
"Rua 15 de Novembro, 24, Centro, SURUBIM" ,
"Avenida José Rodrigues de Jesus, 223 , Indianópolis, CARUARU" ,
"Rua Agamenon Magalhães, 138 , Centro, SURUBIM" ,
"São José, 20 , São José, SURUBIM" ,
"Rua B Três, 714 – (Quadra 03 – LT 15, 18) , Gaibu, CABO DE SANTO AGOSTINHO" ,
"None, None, IPOJUCA" ,
"Rua Alfredo Barbosa de Souza, 17 , Centro, SURUBIM" ,
"Governador Eraldo Gueiros, 20 , Distrito Industrial, ABREU E LIMA" ,
"Rua Engenheiro Sampaio, 05, Rosarinho, RECIFE" ,
"Avenida Conselheiro Rosa e Silva, 1519 – LJ 17, Graças, RECIFE" ,
"None, None, GOIANA" ,
"Avenida Manoel Alves de Carvalho, 598 , Caetano 1, FLORESTA" ,
"Praça Antônio Ferraz, 161 , CENTRO, FLORESTA" ,
"Avenida Antônio Cavalcante Novaes, 283 , COHAB, FLORESTA" ,
"Avenida Duque de Caxias, 433 , Severiano de Moraes Filho , GARANHUNS" ,
"Rua Marquês Amorim, 596, Ilha do Leite, RECIFE" ,
"Avenida João de Barros, 100 , Santo Amaro, RECIFE" ,
"Rua Baixa Verde, 409 , Derby, RECIFE" ,
"None, None, OLINDA" ,
"Rua David Jorge Rodrigues, 232 , Heliópolis, GARANHUNS" ,
"None, None, SÃO BERNARDO DO CAMPO" ,
"Avenida Miguel Nunes de Souza, 390, São Cristóvão, SERRA TALHADA" ,
"Rua João Eugênio de Lima, 143, BOA VIAGEM, RECIFE" ,
"Rua Sávio Napoleão Arcoverde, 206, Coronel Siqueira Campos , ARCOVERDE" ,
"Avenida Severiano José Freire, 174 , São Miguel , ARCOVERDE" ,
"Rua Fernão Dias Paes, 31 , Maurício de Nassau, CARUARU" ,
"Rua Porto Alegre, 239, Nossa Senhora das Dores, CARUARU" ,
"Rua Maria José Dos Santos Moreno, 15, Centro, ARCOVERDE" ,
"Av. José Bonifácio, 442 , São Cristóvão, ARCOVERDE" ,
"Avenida Guararapes, 2282 , Centro, PETROLINA" ,
"Avenida Marechal Mascarenhas de Moraes, 6133 , BOA VIAGEM, RECIFE" ,
"Rua Navegantes, 09, BOA VIAGEM, RECIFE" ,
"Av Josadark Alves de Franca, 403, Santa Mônica, CAMARAGIBE" ,
"Av. Cel. Antônio Japiassú, 752 – Loja 4, Centro, ARCOVERDE" ,
"PC DIDIMO CARNEIRO, 28, centro, SURUBIM" ,
"R EDUARDO DE MORAIS, 25, BAIRRO NOVO, OLINDA" ,
"Av. Agro Industrial, 55, Saramandaia, IGARASSU" ,
"Rua Nossa Senhora Dos Navegantes 431 , Tambaú, JOÃO PESSOA" ,
"Rua da Praia, 3398 , Ponta Negra, NATAL" ,
"Av. Senador Dinarte Medeiros Mariz, 8101 , Ponta Negra, NATAL" ,
"Rua Epaminondas Gracindo, 180 , Pajuçara, MACEIÓ" ,
"Rua Vcos Senador Dinarte Medeiros Mariz, 4077 , Ponta Negra, NATAL" ,
"Av. Boa Viagem, 1070 , Boa Viagem, RECIFE" ,
"Avenida Sátiro Ivo, 32, Magano, GARANHUNS" ,
"Avenida Conselheiro Aguiar, 4.599 , BOA VIAGEM, RECIFE" ,
"Rua Cleto Campelo, 37 – Letra AK, Centro, BUÍQUE" ,
"Praça Barão do Rio Branco , Centro, ARCOVERDE" ,
"Rua dos Arcos, 60 , Poço, RECIFE" ,
"Rua Napoleão Laureano, 46 , PRAZERES, JABOATÃO DOS GUARARAPES" ,
"Rua Araújo Maciel, 104 , CENTRO, PESQUEIRA" ,
"Av Capitão Antônio David, S/N , SANTA ROSA, FLORESTA" ,
"Rua Quintino Bocaiúva n°336, 15 DE NOVEMBRO, GRAVATÁ" ,
"Rua Zeferino Galvão, 55 , CENTRO, PESQUEIRA" ,
"ROD BR 232 KM 209, 900 Galpão O1 , Vila Anápolis, PESQUEIRA" ,
"Avenida Armindo Moura, 646 , PIEDADE, JABOATÃO DOS GUARARAPES" ,
"Avenida Presidente Kennedy, 1.341 , Candeias, JABOATÃO DOS GUARARAPES" ,
"Rua Doutor João Santos Filho, 255 , Parnamirim, RECIFE" ,
"Rua da Liberdade, 475, Centro, ARARIPINA" ,
"Rua Aurora Laerte Cavalcante, 68 , Centro, RECIFE" ,
"Rua Sete de Setembro, 635 , Centro, CAÇAPAVA DO SUL" ,
"Av. Agamenon Magalhaes, 732 , Mauricio de Nassau, CARUARU" ,
"Rua da Esperança, 20 , Vila Moco, PETROLINA" ,
"Rua Alonso Cavalcanti Maciel, 70 , Centro, PESQUEIRA" ,
"Avenida Sete de Setembro, 317 - A , José e Maria, PETROLINA" ,
"Av. Manoel Borba n° 71, Loja 02, Boa Vista, RECIFE" ,
"Sítio Valado, s/n, Zona Rural , CHÃ GRANDE" ,
"Praça João Pessoa, 42, Santo Antônio, GARANHUNS" ,
"Rua Bernardino Guimarães 580, Magano, GARANHUNS" ,
"Rua Vitorino Monteiro, 170 , Santo Antônio, GARANHUNS" ,
"Avenida Osvaldo Cruz, 3331 , São Cristóvão, ARCOVERDE" ,
"Av. Doutor Ulisses Guimaraes, 13 , Jardim Amazonas, PETROLINA" ,
"Rua Barão do Rio Branco, 110 , Magano, GARANHUNS" ,
"na Rua José Bonifácio, 1.210 , Torre, RECIFE" ,
"Avenida Dr. Francisco Correia, 101, Centro, SÃO LOURENÇO DA MATA" ,
"Rua Manoel Clemente, 71 , Santo Antônio, GARANHUNS" ,
"Rua do Riachuelo, 105 , Boa Vista, RECIFE" ,
"Rua Quitéria Medeiros, 253, Santo Antônio, GARANHUNS" ,
"Rua Ricardo Salazar, 134 , Prado, RECIFE" ,
"Av. Guararapes, 1950 , Centro, PETROLINA" ,
"Avenida Bernardo Vieira de Melo, 3.460 , Piedade, JABOATÃO DOS GUARARAPES" ,
"Avenida General Manoel Rabelo, 757, Engenho Velho, JABOATÃO DOS GUARARAPES" ,
"Rua Getúlio Zoby Júnior, 285 , Dom Thiago Postma, GARANHUNS" ,
"Av. Osvaldo Cruz, 1740 , Coronel Siqueira Campos, ARCOVERDE" ,
"PC Manoel Caetano de Brito, 50 , Pitanga, PESQUEIRA" ,
"Rua Pedro Ribeiro, 85 , Matriz, VITÓRIA DE SANTO ANTÃO" ,
"Avenida Doutor Francisco Correia, 1448, Centro, SÃO LOURENÇO DA MATA" ,
"Rua Adolfo Soares, 172 , Centro, OURICURI" ,
"Rua Cícero Bezerra, 25 , Centro, BODOCÓ" ,
"Rua Maestro Carlos Gomes, 103 , Centro, BODOCÓ" ,
"Rua Doutor João Pessoa, 88 , Centro, BODOCÓ" ,
"Av Republica do Líbano, 251, Pina, RECIFE" ,
"Rua Independência, OOL11  , Kennedy, CARUARU" ,
"Rua Emiliano Braga, 1019 , Iputinga, RECIFE" ,
"Rua das calçadas, 154,  Centro, RECIFE" ,
"Rua do Nogueira, 239, São José, RECIFE" ,
"Avenida Governador Agamenon Magalhães, 2936 , Espinheiro, RECIFE" ,
"Rua Maria Generosa de Barros, 50 , Canacui, OURICURI" ,
"Rua Primeiro de Janeiro, 63 , São Pedro, BELO JARDIM" ,
"Praça Sérgio Magalhães, nº 689, Nossa Senhora da Penha, SERRA TALHADA" ,
"Praça Sérgio Magalhães, nº 11, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Manoel Borba, 88 , Santo Antônio, GARANHUNS" ,
"Rua Jacinto Machado, 800, Várzea, RECIFE" ,
"Avenida Ernesto Dourado, 774 , Heliópolis, GARANHUNS" ,
"Rua Coronel João Manguinhos, 837, Bairro Novo, OLINDA" ,
"Comunidade Quilombola do Estivas, 70, Área Rural de Garanhuns, GARANHUNS" ,
"Rua Bernardino Severo Alves, 139, Centro, ARARIPINA" ,
"Estrada do Arraial, 2484, Tamarineira, RECIFE" ,
"Avenida Henrique de Holanda, 39B , Matriz, VITÓRIA DE SANTO ANTÃO" ,
"Avenida Adriano Duque de Godoy Souza, 001 loja 07 e 08,  Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida João Clemente Silva, 86 , Centro, TACAIMBÓ" ,
"Rua Doutor Pedro Augusto Correia de Araújo, 360 , Centro, SÃO LOURENÇO DA MATA" ,
"Rua Siqueira Campos, 279 , Santo Antônio, RECIFE" ,
"Praça Barão do Rio Branco, 151 , Centro, ARCOVERDE" ,
"Rua Francisco Cândido Magalhães, 20 , Triângulo, JUAZEIRO DO NORTE" ,
"Rua da Cocaia, 801, Suape, CABO DE SANTO AGOSTINHO" ,
"Rua Amaro Pereira Cavalcante, 161 , Centro, CABO DE SANTO AGOSTINHO" ,
"Rua Enock Ignacio de Oliveira, 560 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Loc BR 232, SN , Alto Limpo, BELO JARDIM" ,
"Rua Enock Ignacio de Oliveira, 541 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Marechal Floriano Peixoto, 87 , Centro, PAULISTA" ,
"Rua da Aurora, 295 , Boa Vista, RECIFE" ,
"Avenida Conde da Boa Vista, 1096 , Soledade, RECIFE" ,
"Avenida Washington Soares, 3.663 , Edson Queiroz, FORTALEZA" ,
"Rua Sebastião Pinto de Barros, 52, Nossa Senhora das Graças, GRAVATÁ" ,
"Rua Marques de Herval, 58 , Centro, GOIANA" ,
"Rua Irmã Superiora Maria Luiza Rocha, 412 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Praça Sergio Magalhães, 858 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Beberibe, 1678 , Arruda, RECIFE" ,
"Rua dos Navegantes, 691 , Boa Viagem, RECIFE" ,
"Rua Abelardo,45 , Campo Grande, RECIFE" ,
"Av. Conselheiro Aguiar, nº 459, loja 006, Pina, RECIFE" ,
"Rua Antônio Torres Galvão, 158 A , Imbiribeira, RECIFE" ,
"Avenida João de Barros, 1527 , Espinheiro, RECIFE" ,
"Avenida Afonso Magalhães, 411 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Dr. Alcebiades, 172,  Centro, TIMBAÚBA" ,
"Av. Estácio Coimbra, 33, Centro, SÃO JOAQUIM DO MONTE" ,
"Praça Vigário João Inácio, 132, Centro, BUÍQUE" ,
"Rua do Espinheiro, 582 , Espinheiro, RECIFE" ,
"Avenida Coronel Clementino Coelho, 1.800 , Palhinhas, PETROLINA" ,
"Avenida Florentino Alves Batista, 04 , Centro, ARARIPINA" ,
"Rod BR 316, 416, Zona Urbana, ARARIPINA" ,
"ROD BR 423,, SAO JOSE, GARANHUNS" ,
"Rua Dr. José Mariano, 55, Santo Antônio, GARANHUNS" ,
"Rua Loc Engenho Lagoa Verde, S/N, Zona Rural, LAGOA GRANDE" ,
"Rua Marques de Baipendi, 85 , Campo Grande, RECIFE" ,
"Av. República do Líbano, 251 , Pina, RECIFE" ,
"Rua Saldanha Marinho, 423 , Mauricio de Nassau, CARUARU" ,
"Av. Agnelo Arruda Lacerda, 139, São Miguel, ARCOVERDE" ,
"Rua Caio Pereira, 331, Encruzilhada, RE" ,
"Comendador Sá Barreto,280, Candeias, JABOATÃO DOS GUARARAPES" ,
"Rua Domingo Bastos, 91, Encruzilhada, RECIFE" ,
"Praça da Bíblia,80, Centro, GOIANA" ,
"None, Várzea, RECIFE" ,
"Rua Tereza Augusta Maciel, 60 , Centro, BELO JARDIM" ,
"Avenida João Gomes de Lucena, 3410, São Cristóvão, SERRA TALHADA" ,
"Av. Afonso Magalhães, 445, Nossa Senhora da Penha, SERRA TALHADA" ,
"Praça Barão do Pajeú, 940, Nossa Senhora da Penha, SERRA TALHADA" ,
"Praça Doutor Sérgio Magalhães, 686, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Monsenhor João Kerhle, 2536, Várzea, SERRA TALHADA" ,
"Rua do Futuro, 913, Graças, RECIFE" ,
"Rua Governador José Bezerra, 12, Nossa Senhora das Dores, CARUARU" ,
"Rua do Futuro, 913 , Graças, RECIFE" ,
"AV DAS HORTENSIAS,1480, CENTRO, GRAMADO" ,
"AV VINTE DE JANEIRO, S/N, RIO DE JANEIRO, GALEAO" ,
"Rua José Alves da Silveira,685, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Comandante Superior,691, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Enock Ignacio de Oliveira, 969 , Nossa Senhora da Penha, SERRA TALHADA" ,
"Manoel Alves de Carvalho Barros, 2014 , Várzea, SERRA TALHADA" ,
"Rua dos Arcos, 60 , Poço, RECIFE" ,
"Av. Adriano Duque de Godoy Sousa,01, Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida João Gomes de Lucena, 3762 , São Cristóvão , SERRA TALHADA" ,
"Avenida João Gomes de Lucena, 4743, São Cristóvão , SERRA TALHADA" ,
"ROD LMG 800 KM 7,9, s/n, AREA DE APOIO II, LAGOA SANTA" ,
"RUA DOS COLIBRIS, S/N, NOSSA SENHORA DO CUPE, IPOJUCA" ,
"Praça Senador Salgado Filho, s/n, Zona Aeroportuária Santos Dumont, RIO DE JANEIRO" ,
"Quitéria Reis O Almeida,49, Bela Vista, PEDRA" ,
"Avenida Doutor Pedro Jordão, 1040, Maurício de Nassau, CARUARU" ,
"Avenida das Cataratas,6845, Tamanduá, FOZ DO IGUAÇU" ,
"Avenida Sete de Setembro, 1537, Dois de Julho, SALVADOR" ,
"Avenida Coronel Antônio Japiassu,433, Centro, ARCOVERDE" ,
"Praça Doutor Sergio Magalhães,749, Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Afonso Magalhães,163, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua do Futuro,564, Graças, RECIFE" ,
"Avenida Governador Agamenon Magalhães,2939, Espinheiro, RECIFE" ,
"Rua Helena Rodrigues Porto, 40, Centro, ARCOVERDE" ,
"Avenida Djalma Dutra, 494, Heliópolis, GARANHUS" ,
"Avenida Cel Antônio Japiassu, 230, Centro, ARCOVERDE" ,
"Avenida Coronel Antônio Japiassu,370, Centro, ARCOVERDE" ,
"Rua do Cupim, 53, Graças, RECIFE" ,
"Avenida Coronel Antônio Japiassu,470, Centro, ARCOVERDE" ,
"Rua Joca Magalhães, 861, Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Coronel Antônio Japiassu,370, Centro, ARCOVERDE" ,
"Avenida Coronel Antônio Japiassu, 398, Centro, ARCOVERDE" ,
"Praça Sérgio Magalhães, 680, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Antônio Biliu, 166, Centro, VENTUROSA" ,
"Estrada do Encanamento, 846, Casa Amarela, RECIFE" ,
"Avenida Adriano Duque de Godoy Souza,001, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Agostinho Nunes de Magalhães,51, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua Carneiro Vilela, 324, Aflitos, RECIFE" ,
"Avenida Governador Agamenon Magalhães, 2939, Espinheiro, RECIFE" ,
"Rua Coronel Alfredo Duarte, Afogados, RECIFE" ,
"Avenida Agamenon Magalhães,2656, Espinheiro, RECIFE" ,
"Rua Manoel Graciliano de Souza, 840, Jardim Atlântico, OLINDA" ,
"Rua Benfica,728, Madalena, RECIFE" ,
"Avenida Agamenon Magalhães,834, Maurício de Nassau, CARUARU" ,
"Rua Pedro Negro,1300, Orange, ILHA DE ITAMARACÁ" ,
"Rua Agostinho Nunes de Magalhães,239, Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Doutor Idelfonso, 166, Heliópolis, GARANHUNS" ,
"Rua Visconde de Abaete, 113, Tamarineira, RECIFE" ,
"Rua Dom Jose 167 , Santo Antonio, GARANHUNS" ,
"Praca Jardim 98 , Santo Antonio, GARANHUNS" ,
"Rua Dom Jose 77 , Santo Antonio, GARANHUNS" ,
"Rua Doutor José Mariano 164, Santo Antonio, GARANHUNS" ,
"Rua Professor José Candido Pessoa 743 , Bairro Novo, OLINDA" ,
"Avenida Manoel Alves de Carvalho, 650, Caetano II, FLORESTA" ,
"Rua Sebastião Alves, 220, Tamarineira, RECIFE" ,
"Praça Cap Emilio Novaes, 167, Centro, FLORESTA" ,
"Rua Dário Ferraz, 307, Centro, FLORESTA" ,
"Rua Emídio Quirino de Sá, 300, Santa Rosa, FLORESTA" ,
"Rua Doutor Tito Rosas 14, Centro, FLORESTA" ,
"Rua Cel Manoel Olímpio de Menezes 08 , Centro, FLORESTA" ,
"Rua Doutor Aniceto Varejão, 415 , Candeias, JABOATÃO DOS GUARARAPES" ,
"Rua Doutor Aniceto Varejão, 415 , Candeias, JABOATÃO DOS GUARARAPES" ,
"Rua Rosa Pereira da Cruz 53 , Desterro, ABREU E LIMA" ,
"Avenida Manoel Alves Machado, 326, Francisco Simão dos Santos Figueira, GARANHUNS" ,
"Rua Padre Felix Barreto,40, Centro, BODOCÓ" ,
"ROD. BR-101 NOVO TRACADO – POSTO PICHILAU , Prazeres, JABOATÃO DOS GUARARAPES" ,
"Av. Afonso Magalhães, 856, São Cristovão, SERRA TALHADA" ,
"Rua Dom Manoel de Paiva,335, Heliópolis, GARANHUNS" ,
"AV.BERNARDO VIEIRA DE MELO, 3.310  - LOJA 15 - GALERIA SHOPPING VILLAGE , PIEDADE, JABOATÃO DOS GUARARAPES" ,
"Rua Visconde de Jequitinhonha, 209, sala 602 - Empresarial Visconde Jequitinhonha , Boa Viagem , RECIFE" ,
"Av. Prof. Luís Freire, 700 - Bloco C, sala 34, 1º Andar, Cidade Universitária, RECIFE" ,
"Av. Fernando Pessoa de Queiroz Nº 536 , Prado , PESQUEIRA" ,
"Av. Visconde de Suassuna, 594, Santo Amaro, RECIFE" ,
"Av. Visconde de Suassuna, 594, Santo Amaro, RECIFE" ,
"Rua Severina Peixoto, nº 106, Santo Antônio, GARANHUNS" ,
"Avenida Santo Antônio,270, Santo Antônio, GARANHUNS" ,
"Rua do Futuro, 858, Graças, RECIFE" ,
"Rua Ary Barroso,137, Santo Antônio, GARANHUNS" ,
"Avenida Bom Pastor, 600, Aluísio Pinto, GARANHUNS" ,
"Rua Severiano Peixoto, 126, Santo Antônio, RECIFE" ,
"Rua do Futuro, 858, Graças, RECIFE" ,
"3° R Rua, 98, Centro, FLORESTA" ,
"Rua Padre Felix Barreto, 128,  Centro, BODOCÓ" ,
"Rua Senador José Henrique, 141, Ilha do Leite, RECIFE" ,
"Rua Men de Sá, 23, Indianópolis, CARUARU" ,
"Rua Alferes Jorge, 398, Indianópolis, CARUARU" ,
"Praça Pedro Souza, 39, Nossa Senhora das Dores, CARUARU" ,
"Av. Dioguinho,4189 , Praia do Futuro, FORTALEZA" ,
"Avenida Sul Governador Cid Sampaio, Imbiribeira, RECIFE" ,
"Praça de Casa Forte, 409, Casa Forte, RECIFE" ,
"Rua da Prosperidade, 32, São josé, RECIFE" ,
"Rua Antônio Frederico Ozanan, Brigadeira, CANOAS" ,
"None, Avenida Portugal, 976, UNIVERSITÁRIO" ,
"Rua Itapeva, 26, Centro, CENTRO" ,
"Avenida João Gomes de Lucena, 3452, São Cristóvão, SERRA TALHADA" ,
"None, Rua severino Hermínio de Carvalho, 739, SERROTÃO" ,
" Rua Marquês Amorim,444,  Ilha do Leite, RECIFE" ,
"Rua  Real da Torre, Madalena , RECIFE" ,
"Av. Agamenon Magalhães, 448, Prado , GRAVATÁ" ,
"Rua José Raimundo de Castro, 270, Cohab I, BELO JARDIM" ,
"Rua Capitão Emilio Novaes, 252, Centro, PE" ,
"Estrada dos remédios, 367, Afogados, RECIFE" ,
"Rua 12 R Pereira Maciel, 167, Centro, FLORESTA" ,
"Avenida Santos Dumont 332, Aflitos, RECIFE" ,
"Rua Elvira Vale de Oliveira 365, Sebastião Simão dos Santos, PEDRA" ,
"Avenida Santo Antônio 117, Centro, GARANHUNS" ,
"Avenida Rio Branco, 182 , Nossa Senhora das Dores, CARUARU" ,
" Rua Vitória Maria Torres, 28, Atrás da Banca, PETROLINA" ,
"Rua 31 de Março 179, Ipsep, RECIFE" ,
" Rua Itacaré, 247, Imbiribeira, RECIFE" ,
"Praça de Casa Forte 465, Casa Forte, RECIFE" ,
"Rua Horizonte 41, Boa Viagem, RECIFE" ,
"Rua Coronel Antônio Marinho, 36 ,  Ayrton Maciel, BELO JARDIM" ,
"Rua Couto Magalhães, 312 , Rosarinho, RECIFE" ,
"Rua Wanderlandia, 17, Cajueiro, RECIFE" ,
"Rua Lia de Andrade Barreto, 88 , Centro, RIO FORMOSO" ,
"Rua Djalma Farias, 251, Torreão , RECIFE" ,
"Rua José Duca da Silva, 22, Boa Vista, GARANHUNS" ,
"Av. Adjar da Silva Casé, n° 800, Indianópolis, CARUARU" ,
"Vila do Vitorino, 17, Vila do Vitorino, RIACHO DAS ALMAS" ,
"Rua Agostinho Nunes de Magalhães, Nossa Senhora da Penha, SERRA TALHADA" ,
" Av. Adriano Duque de Godoy Sousa, 1, Nossa Senhora da Penha, SERRA TALHADA" ,
"Avenida Norte Miguel Arraes de Alencar, 3003, Encruzilhada, RECIFE" ,
"Av. Euclides de Carvalho, 13, Centro, SÃO JOSÉ DO BELMONTE" ,
"Rua Cento e Quarenta e Nove, 175 , Caetes I, ABREU E LIMA" ,
"Avenida Conde da Boa Vista, 610, Boa Vista, RECIFE" ,
"Rua Geriquiti, 48,  Boa Vista, RECIFE" ,
"Avenida Bernardo Vieira de Melo, 1730, Piedade, JABOATÃO DOS GUARARAPES" ,
"Rua do Progresso, 405, Soledade, RECIFE" ,
"Rua José Martins Sobrinho, 330, Andorinha, CARUARU" ,
"Avenida Bernardo Vieira de Melo, 3462, Piedade, JABOATÃO DOS GUARARAPES" ,
"Avenida Olavo Gomes de Oliveira, 635, Saudade, SERRA TALHADA" ,
"Avenida Getúlio Vargas, 150,  Centro, TRIUNFO" ,
"Rua José Bonifácio, 205 , Madalena, RECIFE" ,
"Rua do Brum, 455, Bairro do Recife, RECIFE" ,
" Avenida Vera Cruz 735, São Francisco, CARUARU" ,
"Rua Professor José Carneiro, 74, Encruzilhada, RECIFE" ,
"Rua Domingos Siqueira, 3 , Centro, SÃO JOSÉ DO EGITO" ,
"Rua Antônio Pereira Amorim, 2319, Centro, TABIRA" ,
"EMANOEL PEREIRA DA SILVA, Rua das Algas Marinhas, 64, JAGUARIBE" ,
"Rua Inocêncio Gomes de Andrade, 696, Nossa Senhora da Penha, RECIFE" ,
"Rua Real da Torre, 762 -,  Madalena, RECIFE" ,
"Rua do Amparo, 62, Amparo, OLINDA" ,
"Rua Doutor João Costa, 201, Bongi, RECIFE" ,
" Rua Tabira 171, Boa Vista, RECIFE" ,
"Estrada do Encanamento, 480, Parnamirim, RECIFE" ,
"Avenida Conselheiro Rosa e Silva, 670, Graças, RECIFE" ,
"Avenida Lins Petit, n° 100, Paissandu, RECIFE" ,
"Rua Bernardo Guimarães, S/N , Santo Amaro, RECIFE" ,
"Rua do Príncipe, 526, Boa Vista, RECIFE" ,
"Coronel João Ribeiro, 53, Bairro Novo, OLINDA" ,
"Rua Eugênio de Lima, 143 , Boa Viagem, RECIFE" ,
"Praça Gonçalo Gomes, 38,  Centro, TABIRA" ,
"Avenida Raimundo Ferreira Pires, 49, Jureminha, TABIRA" ,
" Avenida Marijó de Farias, 153 , Universitário, CARUARU" ,
"Rua Raimundo Gomes Gondin, 65, Boa Viagem, RECIFE" ,
" Rua comandante Dantas Superior, 691, Nossa Senhora da Penha, SERRA TALHADA" ,
"Rua do Rócio, 199, Vila Olímpia, SÃO PAULO" ,
"Rua Bernardo Guimarães, 39, Santo Amaro, RECIFE" ,
"Rua Antônio Ferreira Campos, 4366 , Candeias, JABOATÃO DOS GUARARAPES" ,
"Rua General Jose Semeão, 115, Santo Amaro, RECIFE" ,
"Rua Bernardo Guimarães, 29 - Box 29, Santo Amaro, RECIFE" ,
"PRAÇA ISMAEL GOUVEIA – 233 – CENTRO – PALMARES - PE, CENTRO, PALMARES" ,
"R DO PRINCIPE, 526, BOA VISTA, RECIFE" ,
"R GENERAL JOSE SEMEAO, 115, SANTO AMARO, RECIFE" ,
"Av. Engenheiro Domingos Ferreira, 4371, sl. 0102, Boa Viagem, RECIFE" ,
"Rua Doutor Manoel Borba n.08, Centro, GOIANA" ,
"Rua Nobre de Lacerda,98, Madalena, RECIFE" ,
" Av. Bernardo Vieira de Melo, 1243, Piedade, JABOATÃO DOS GUARARAPES" ,
"Avenida Rio  Branco, 128, Centro, CARUARU" ,
"Rua Joaquim Felipe, 119, Soledade, RECIFE" ,
"Rua Carlos Pereira Falcão, 760 ,  Boa Viagem, RECIFE" ,
"Rua Rui Barbosa, 323, Janga, PAULISTA" ,
" Avenida Santa Marina, 2569, Vila Albertina, SÃO PAULO" ,
"Rua do Riachuelo, 105, Boa Vista, RECIFE" ,
" Rua Antônio Justino de Arruda, 56 , Centro, SURUBIM" ,
"Avenida Doutor Cláudio José Gueiros Leite, 3723, Janga, PAULISTA" ,
"Rua Conselheiro Severino Francisco Alves, 138, Livramento, VITÓRIA DE SANTO ANTÃO" ,
"Rua Jean Emile Favre, 422, Imbiribeira, RECIFE" ,
"ROD PE-09 - KM 06, LOTES, 5, 6, 7, 8, 9 E 10- QUADRA - H, S/N, Porto de Galinhas, IPOJUCA" ,
"Rua Ipê Roxo , s/n, Cupe, IPOJUCA" ,
"Avenida Corifeu de Azevedo Marques, n° 3097, Butantã, SÃO PAULO" ,
"Rua Arthur Pernambuco, 917, Janga, PAULISTA" ,
"Avenida Historiador Pereira da Costa, 234 , Centro, CABO" ,
"Rua da Vila, 01, Vila Doutor Manoel Clementino, CABO" ,
"Rua Frei Jaboatão, 280, Torre, RECIFE" ,
"Rua do Futuro, 425, Graças, RECIFE" ,
"Rua Gervásio Pires, 826 -, Santo Amaro, RECIFE" ,
"Rua Miguel Ribeiro, 60, Centro, RECIFE" ,
"Rua Afonso Pena, 165, Santo Amaro, RECIFE" ,
"Avenida Alfredo Lisboa, S/N, Recife, RECIFE" ,
"Rua Sebastião Alves, 144, Tamarineira, RECIFE" ,
"Rua Sebastião Alves, 156, Tamarineira, RECIFE" ,
"Avenida Visconde de Albuquerque, 796, Madalena, RECIFE" ,
" Avenida República do Líbano, 251, Pina, RECIFE" ,
"Avenida República do Líbano, 251, Pina, RECIFE" ,
"Rua Dom Mota, 62 , Riacho do Gado Tabira, TABIRA" ,
"Avenida Olinda Dom Helder Câmara, 171, Olinda, SANTA TEREZA" ,
"Rod. PE-15, 242, Centro, PAULISTA" ,
"Rod Pe - 15, 242, Centro, PAULISTA" ,
" Avenida Almirante Paulo Moreira, 252, Garapu, CABO" ,
"Rua Odorico Mendes, 70 , Campo Grande, RECIFE" ,
"Rua Barão de Souza Leão, 195, Boa Viagem, RECIFE" ,
" Rua Francisco de Assis da Silva Teixeira, 408, Cohab, CABO DE SANTO AGOSTINHO" ,
" Praça Presidente Getúlio Vargas, 129, Nossa Senhora das Dores, CARUARU" ,
"Rua Cajueiro, 47, Salgadinho, OLINDA" ,
"RUA MAJOR CODECEIRA, 190, Santo Amaro, RECIFE" ,
"Avenida República do Líbano, 251, Pina, RECIFE" ,
"Avenida Monsenhor Ângelo Sampaio, 100, Centro, PETROLINA" ,
"Rua João Romão de Oliveira, 271, São Cristóvão, SERRA TALHADA" ,
"Rua Vereador Rodrigues do Nascimento, 43, Centro, SERRA TALHADA" ,
"Avenida Luiz Cosme de Magalhães, 441 , Tancredo Neves, SERRA TALHADA" ,
"Rua Padre Carapucceiro, 777, Boa Viagem, RECIFE" ,
" Rua Fecomércio, 101, Anchieta, PORTO ALEGRE -" ,
"Estrada do Encanamento, 389 , Parnamirim, RECIFE" ,
"Praça Pedro Pereira Primo, 58, Alagadiço, JUAZEIRO" ,
"Avenida Bernardo Vieira de Melo, 3476, Piedade, JABOATÃO DOS GUARARAPES" ,
" Avenida Sport Clube do Recife, 0 , Ilha do Leite, RECIFE" ,
"Avenida José Augusto Moreira, 975, Casa Caiada, OLINDA" ,
" Avenida Boa Viagem, 97 , Pina, RECIFE" ,
"Rua Barros Barreto, 346, Santo Amaro, RECIFE" ,
"Rod Br 101 Sul, S/N , Prazeres, JABOATÃO DOS GUARARAPES" ,
"Rua projetada, 147 , Cohab, BODOCÓ" ,
"Rua do Hospício, 171, Boa Vista, RECIFE" ,
" Avenida José Pires da Silva, 222 , Centro, BODOCÓ" ,
"Rua Cento e Doze, 125,  Caetes I, RECIFE" ,
"Rua Nossa Senhora dos Prazeres, 20, Jardim Jordão, RECIFE" ,
"None, None, RECIFE" ,
" Rua Coronel Francisco Galvão, 159 - , Piedade, JABOATÃO DOS GUARARAPES" ,
"R. Sant'Anna, 233, Casa Forte, RECIFE" ,
"None, Madalena, RECIFE" ,
"Rua Jaguaribe,41,  Madalena, RECIFE" ,
"Avenida Antônio de Góes, 869,  Pina, RECIFE" ,
"Rua Carlos Pereira Falcão, nº 121, Boa Viagem, RECIFE" ,
" Estrada da Mumbeca, nº 9500, Aldeia, CAMARAGIBE" ,
"Rua Nestor Silva, nº 130, Casa Forte, RECIFE" ,
" Avenida Major Manoel de Freitas, nº 48 , Mauricio de Nassau, CARUARU" ,
"Av Porfessor Joaquim Cavalcanti, nº s/n ,  Iputinga, Recife" ,
"Rua Conselheiro Portela, nº 665,  Aflitos, Recife" ,
"Rua Rio das Contas, nº 84, Ibura de Baixo,  Recife " ,
"Rua Santo Antônio, nº 1040, Centro, PE" ,
" Rua sessenta e sete, nº 326,  Jardim Paulista Baixo, PAULISTA" ,

]

geolocalizador = Bing(api_key=bing_api_key)

lista_de_parceiros = []

for endereco in enderecos:
    try:
        localizacao = geolocalizador.geocode(endereco, timeout=10)
        
        if localizacao:
            parceiro = {
                "id": len(lista_de_parceiros) + 1,
                "fantasia": f"Parceiro {len(lista_de_parceiros) + 1}",
                "endereco": endereco,
                "latitude": localizacao.latitude,
                "longitude": localizacao.longitude
            }
            
            lista_de_parceiros.append(parceiro)
        else:
            print(f"Não foi possível encontrar a localização para o endereço: {endereco}")
    except GeocoderTimedOut as e:
        print(f"Tempo limite excedido para o endereço: {endereco}")

# Salvando os parceiros em um arquivo JSON com codificação UTF-8
with open("parceiros.json", "w", encoding="utf-8") as arquivo_json:
    json.dump(lista_de_parceiros, arquivo_json, ensure_ascii=False, indent=4)

print("Parceiros foram salvos no arquivo 'parceiros.json'.")
